"""
Django settings for ccu_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY',None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_filters',
    "django_celery_beat",
    "accounts.apps.AccountsConfig",
    "labs.apps.LabsConfig",
    "operators.apps.OperatorsConfig",
    "application.apps.ApplicationConfig",
    "diffdevices.apps.DiffdevicesConfig",
    'quotagroup.apps.QuotagroupConfig',
    'journal.apps.JournalConfig',
    'probe.apps.ProbeConfig',
    'publication.apps.PublicationConfig',
    'suggestion.apps.SuggestionConfig',
    'cryst_chemist.apps.CrystChemistConfig',
    'structurer.apps.StructurerConfig',
    'notification.apps.NotificationConfig',
    'widget_tweaks',
]
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CELERY_BEAT_SCHEDULE = {
#     "test_task": {
#         "task": "services.email_service.test_task",
#         "schedule": 15.0,
#     },
# }

AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ccu_project.urls"

LOGIN_FAILURE_LIMIT = 5     # Макс. число попыток входа
LOGIN_COOLOFF_TIME = 1      # Блокировка на 1 час после 5 ошибок

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ccu_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": "db",   # имя сервиса в docker-compose
        "PORT": 5432,
    }
}
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email" # new
ACCOUNT_EMAIL_REQUIRED = True # new
ACCOUNT_UNIQUE_EMAIL = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailAuthBackend'
]
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"


# Celery
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_IMPORTS = ('services.tasks', 'services.email_service')
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = os.getenv('TIME_ZONE',None)

USE_I18N = True

USE_TZ = True

# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {  # root logger
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Сюда collectstatic сложит всё (эта папка подключена в docker-compose)
STATIC_ROOT = BASE_DIR / "static"

# Дополнительные папки со статикой, которые нужно собрать
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EM_HOST", None)
EMAIL_PORT = os.getenv("EM_PORT", None)
EMAIL_HOST_USER = os.getenv("EM_HOST_USER", None)
EMAIL_HOST_PASSWORD = os.getenv("EM_HOST_PASSWORD", None)
DEFAULT_FROM_EMAIL = os.getenv("DFLT_FROM_EMAIL", None)
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
SITE_NAME = os.getenv("SITE_NAME", None)
SITE_URL = os.getenv("SITE_URL", None)
