from django import template
from django.core.cache import cache
from ccu_project.constants import QT_ST_GRPH
import logging

logger = logging.getLogger(__name__)

register = template.Library()

@register.simple_tag
def get_daily_quota_graph():
    """
    Template tag to retrieve the daily quota usage graph from cache.

    This template tag fetches the cached Plotly JSON graph generated by
    plot_quota_time_new() functions for display in Django templates.

    Returns:
        str or None: Plotly JSON graph data if available in cache, None otherwise.
    """
    return cache.get(QT_ST_GRPH, None)